### ISSUE TITLE
Fanout panic on closing channel

### ISSUE THREAD

**Issue by alitvak69** [networkservicemesh/fanout#32]
Coredns died.  Below are logs and configuration. 

2021-01-06T10:12:50.856608991-08:00 coredns-mserver-pbxsm-staging 143 panic: send on closed channel
2021-01-06T10:12:50.856637258-08:00 coredns-mserver-pbxsm-staging 143
2021-01-06T10:12:50.856647131-08:00 coredns-mserver-pbxsm-staging 143 goroutine 115942 [running]:
2021-01-06T10:12:50.856656343-08:00 coredns-mserver-pbxsm-staging 143 github.com/networkservicemesh/fanout.(*Fanout).ServeDNS.func1(0x3, 0xc00060e870, 0xc000c1c300)
2021-01-06T10:12:50.856677605-08:00 coredns-mserver-pbxsm-staging 143      /go/pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20201216200329-84902c6419cb/fanout.go:86 +0x65
2021-01-06T10:12:50.85668812-08:00 coredns-mserver-pbxsm-staging 143 created by github.com/networkservicemesh/fanout.(*Fanout).ServeDNS
2021-01-06T10:12:50.856699111-08:00 coredns-mserver-pbxsm-staging 143      /go/pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20201216200329-84902c6419cb/fanout.go:83 +0x1e5
2021-01-06T10:12:50.861503396-08:00 coredns-mserver-pbxsm-staging exited with error: exit status 2

. {
    bind 127.0.0.1
    log {
      class denial
      class error
    }	
    fanout . 10.1.51.210:53 10.1.51.211:53 10.1.51.212:53
    #forward . 10.1.51.210:53 10.1.51.211:53 10.1.51.212:53
    errors
    cache {
      success 10000 3600 5
      denial 10000 3600 5
    }
}

consul {
    bind 127.0.0.1
    log {
      class denial
      class error
    }	
    fanout . 10.1.73.1:53 10.1.73.2:53 10.1.73.3:53
    errors
    cache {
      success 10000 5 5
      denial 10000 5 5
    }
}

la.consul {
    bind 127.0.0.1
    log {
      class denial
      class error
    }	
    fanout . 10.0.73.43:53 10.0.73.40:53 10.0.73.28:53
    errors
    cache {
      success 10000 5 5
      denial 10000 5 5
    }
}

la-prod-la2.consul {
    bind 127.0.0.1
    log {
      class denial
      class error
    }	
    fanout . 10.0.74.17:53 10.0.74.18:53 10.0.74.19:53
    errors
    cache {
      success 10000 5 5
      denial 10000 5 5
    }
}

chi-pbx.consul {
    bind 127.0.0.1
    log {
      class denial
      class error
    }	
    fanout . 10.1.73.1:53 10.1.73.2:53 10.1.73.3:53
    errors
    cache {
      success 10000 5 5
      denial 10000 5 5
    }
}

chi-prod-xcast.consul {
    bind 127.0.0.1
    log {
      class denial
      class error
    }	
    fanout . 10.1.73.23:53 10.1.73.22:53 10.1.73.15:53
    errors
    cache {
      success 10000 5 5
      denial 10000 5 5
    }
}

**Comment by denis-tingaikin** [comment]
@alitvak69 Thanks for the issue reported! The problem should be fixed.
